Count reg function
UBC-MDS/aridanalysis_py pull request #60
Opened 2021-03-06 22:22 UTC by ansarusc

Hey guys, this is the final version of the count regression function. It wraps statsmodels so that categorical features can be more easily applied as well as interactive models for inference. Give it a try! All 13 tests we have so far passed.

2021-03-06 22:33 UTC, cmmclaug requested changes
Biggest thing is to keep one copy of healthdata in a data folder, and reference. You may have to add this folder to path at the top of both test_aa and aa folders. See how I did it for the /aridanalysis folder.

2021-03-06 22:33 UTC, cmmclaug commented on aridanalysis/aridanalysis.py
> +    assert isinstance(con_features, list), "ERROR: INVALID LIST INTPUT PASSED"
Maybe when we have some time, add these to error_strings.py.

2021-03-06 22:33 UTC, cmmclaug commented on aridanalysis/aridanalysis.py
> +        if len(cat_list) > 0:
Maybe a comment here in the future, this is only because of the weird statsmodel interface allowing R style regression function syntax.

2021-03-06 22:33 UTC, cmmclaug commented on aridanalysis/aridanalysis.py
> +        for i in con_features[0:]:
A three-level nested for-loop is a bit eye-catching. Is there any way to simplify this?

2021-03-06 22:33 UTC, cmmclaug commented on aridanalysis/badhealth.csv
> +"","numvisit","badh","age"
We should move this to a <repo>/data folder.

2021-03-06 22:33 UTC, cmmclaug commented on tests/badhealth.csv
> +"","numvisit","badh","age"
Again, keep one copy in <repo>/data and load from there.

2021-03-07 03:15 UTC, nphaterp reviewed
LGTM

2021-03-07 03:15 UTC, cmmclaug approved these changes
Looks good!

2021-03-07 03:15 UTC, merged